### ISSUE TITLE
Requirement : Appointment listing based on Client Id

### ISSUE THREAD

**Issue by Anurag-14** [ProdioDesignWorks/appointment-module-prodio#5]
**Requirement**: 
Hello @beingshashi  ,
I have used your Appointment Module to Integrate Appointments in my Product,
**Scenario**:
Clients can receive appointments through multiple sites,and Clients should be able to view all his  appointments arrived from various  sites. 
**Request** : Appointments based on bizClientId only.
Thank you.

**Comment by beingshashi** [comment]
@Anurag-14 : I have updated the respective [Appointment APIs](https://github.com/ProdioDesignWorks/appointment-services-prodio) Please use the latest version. SiteId is now optional.

**Comment by Anurag-14** [comment]
@beingshashi : Thank you sir.
