### ISSUE TITLE
Requirement : Appointment name key 

### ISSUE THREAD

**Issue by Anurag-14** [ProdioDesignWorks/appointment-module-prodio#9]
hello @beingshashi ,
I have used your appointment module to integrated appointments in my product .
**Scenario** 
   I have Appointment dashboard  in my product , which consists of list of appointments have been booked. So it would be quite helpful if you will provide me **appointmentName** in create Appointment payload.
Thank you

**Comment by beingshashi** [comment]
@Anurag-14: Done. Please update the latest module and services.
